name: lk_cric_park
description: "Cricket Ground Slot Booking App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

#  Firebase Packages
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  firebase_messaging: ^15.1.6

#  State Management
  get: ^4.6.6

  flutter_animate: ^4.5.2
  lottie: ^3.3.0
  carousel_slider: ^5.0.0

  url_launcher: ^6.3.1
  intl: ^0.20.1
  get_storage: ^2.1.1

  connectivity_plus: ^6.1.1

  flutter_otp_text_field: ^1.4.0+2
  smooth_page_indicator: ^1.2.0+3

  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

# Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/images/
     - assets/images/logo/
     - assets/images/animations/
     - assets/images/on_boarding_images/
     - assets/images/banners/
