name: lk_cric_park
description: "Cricket Ground Slot Booking App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter


#  State Management
  get: ^4.6.6

  flutter_animate: ^4.5.2
  lottie: ^3.3.0

  url_launcher: ^6.3.1
  intl: ^0.20.1
  get_storage: ^2.1.1

  connectivity_plus: ^6.1.1

  flutter_otp_text_field: ^1.4.0+2

# Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/images/
     - assets/images/logo/
